export const BOOKS = [
    {
        id: 1,
        category: 1,
        name: 'NOVELA A',
        description: 'NOVELA A',
        weight: '1/2 kg',
        price: 10,
    },
    {
        id: 2,
        category: 1,
        name: 'NOVELA B',
        description: 'NOVELA B',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 3,
        category: 2,
        name: 'NOVELA C',
        description: 'NOVELA C',
        weight: '1/3 kg',
        price: 20,
    },
    {
        id: 4,
        category: 2,
        name: 'NOVELA D',
        description: 'NOVELA D',
        weight: '1/3 kg',
        price: 25,
    },
    {
        id: 5,
        category: 3,
        name: 'NOVELA E',
        description: 'NOVELA E',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 6,
        category: 3,
        name: 'NOVELA F',
        description: 'NOVELA F',
        weight: '1/3 kg',
        price: 20,
    },
    {
        id: 7,
        category: 4,
        name: 'NOVELA F',
        description: 'NOVELA F',
        weight: '1/4 kg',
        price: 15,
    },
    {
        id: 8,
        category: 4,
        name: 'NOVELA F',
        description: 'NOVELA F',
        weight: '1/3 kg',
        price: 20,
    },
]